[phases.setup]
nixPkgs = ["nodejs-18_x", "npm-9_x"]

[phases.install]
cmds = [
    "cd backend-nestjs",
    "npm ci"
]

[phases.build]
cmds = [
    "cd backend-nestjs", 
    "npm run build"
]

[start]
cmd = "cd backend-nestjs && npm run start:prod"
