services:
  # Backend API Service
  - type: web
    name: owtdeparq-backend
    env: node
    plan: free
    buildCommand: cd backend-nestjs && npm install && npm run build
    startCommand: cd backend-nestjs && npm run start:prod
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        fromDatabase:
          name: owtdeparq-db
          property: connectionString
      - key: GROQ_API_KEY
        sync: false
      - key: FIREBASE_PROJECT_ID
        sync: false
      - key: FIREBASE_CLIENT_EMAIL
        sync: false
      - key: FIREBASE_PRIVATE_KEY
        sync: false

  # Frontend Static Site
  - type: web
    name: owtdeparq-frontend
    env: static
    plan: free
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/build
    pullRequestPreviewsEnabled: false
    envVars:
      - key: REACT_APP_API_BASE_URL
        fromService:
          type: web
          name: owtdeparq-backend
          property: host

databases:
  - name: owtdeparq-db
    databaseName: owtdeparq
    user: owtdeparq_user
    plan: free